### ISSUE TITLE
Suggestion: Can we add Season 1-3 pages? 

### ISSUE THREAD

**Issue by phScholz** [kealsera/rikki#106]
If someone like me would provide the content of end season ranking for previous seasons and playoffs links, would you add them to the Season menus?

**Comment by kealsera** [comment]
Is this something you really want to have?
We would have to recreate all those teams manually, manually assining them to divisions, manually uploading logos.... that's like days of work.

And even then, it would probably lowest priority possible

**Comment by kealsera** [comment]
@phScholz

**Comment by pppws** [comment]
do we need the teams as links? it coud be just a static hall of fame table?

**Comment by kealsera** [comment]
Yes. We need the data inorder for the frontend to render them.

**Comment by phScholz** [comment]
I would like to archive the history of lounge and see the possibility that new users will find it awkward that seasons start with number 4. I see that the connection to the database is a lot of work for little outcome... And also want to know if it would be possible to put in static pages which just have the same look as a in-between solution for max outcome

**Comment by kealsera** [comment]
I wouldn't recommend a static page with the same looks. That's even more work - I for one, will not do. But you can always go to our test domain and try a static page yourself.

**Comment by pppws** [comment]
how do i access the testpage?

**Comment by kealsera** [comment]
onenote
