### ISSUE TITLE
I can't update my role to bruiser, It returns an error page. Is this a known bug?

### ISSUE THREAD

**Issue by kealsera** [kealsera/rikki#11]

**Comment by bdemirel** [comment]
This problem occurs not only with role updates, but with any other profile update if the first new password field is filled but not the second one. I think this is intended as save button saves every tab, but an error field describing the problem would be better than just resulting a page error with no specific information.

**Comment by kealsera** [comment]
@bdemirel is assigned to rework the profile field in a way, that this error will not happen anymore.

We may want to change all Save Things Pages in a way, that it allows per section Save & Save all at once.

**Comment by kealsera** [comment]
@bdemirel reopened due to refactoring needings

**Comment by kealsera** [comment]
https://github.com/kealsera/rikki/commit/058a312ab6480a72ad10c487f71606cb9459be87
