### ISSUE TITLE
Add map bans to the website

### ISSUE THREAD

**Issue by Astraeus-** [kealsera/rikki#126]
Questions from: Pieczar | IX Kohorta

1. Is it possible to add map veto to site?(like we adding maps after games) info about map picks is awesome, but without map veto is a little bit odd.

2. Do the coinflip on site when swiss pairing happens.

3. Do map bans on site instead of in discord match lounges

**Comment by Fabian-Sommer** [comment]
I like doing the coinflip when the game happens, its add a bit of excitement.
Using Discord for map bans is fine. It also provides a place for captains, casters, mods etc. to communicate between games.
Having captains enter map bans is something we could do. That data may be incomlete and sometimes wrong, but that is better than no data. I will make a proper issue out of it.
