### ISSUE TITLE
Add API abilities to heroeslounge

### ISSUE THREAD

**Issue by kealsera** [kealsera/rikki#19]

**Comment by phScholz** [comment]
Matches of Season X Round Y ... with results if already played

**Comment by phScholz** [comment]
Teams of Season X Round Y Match Z

**Comment by phScholz** [comment]
Replay of Season X Round Y Match Z Game 1/2/3

**Comment by phScholz** [comment]
Team logo of Team X

**Comment by phScholz** [comment]
Standings for Season X Division Y

**Comment by phScholz** [comment]
Changes to the roster of Team X with date/time stamps

**Comment by phScholz** [comment]
Matches Scheduled for /YYYY/MM/DD

**Comment by phScholz** [comment]
Matches of Team X in Season Y ... with results if already played

**Comment by phScholz** [comment]
Teams X of Player Y with joining/leaving Date/time stamps

**Comment by phScholz** [comment]
Links to twitter/facebook/twitch/website of User X or Team Y

**Comment by kealsera** [comment]
Links to twitter/facebook/twitch/website of User X or Team Y
Teams X of Player Y with joining/leaving Date/time stamps
Matches of Team X in Season Y ... with results if already played
Matches Scheduled for /YYYY/MM/DD
Changes to the roster of Team X with date/time stamps
Standings for Season X Division Y
Team logo of Team X
Replay of Season X Round Y Match Z Game 1/2/3
Teams of Season X Round Y Match Z
Matches of Season X Round Y ... with results if already played

**Comment by Takaloy** [comment]
if I want to order by priority, I'd go for 

1. Teams X of Player Y with joining/leaving Date/time stamps
2. Teams of Season X Round Y Match Z
3. Replay of Season X Round Y Match Z Game 1/2/3

**Comment by kealsera** [comment]
https://github.com/kealsera/rikki/commit/ac19ebd41c76f54a623866a3a027eb179e93b430

**Comment by shooter92** [comment]
Sorry for newbie-programmer content...
As a Caster it would be nice to generate Caster-related Overlays.

- Requirement: The Website shall know which match is actually running (compare matchtime with actual time) and wich casters are assigned for the match.

- The goal: get a site at Profile --> Your overlays (per example) where links are shown for multiple overlays (design given by CI). This takes about 10 mins away from casters to prepare their OBS FOR EACH MATCH and prohibits typos.

- I can build you a website with html/css which represents the actual overlay without the yellow informations. But I need to know how i can get all the yellow informations related on a given castername. And how i can receive and implement the data (never used php, but a little knowledge in JS / JSON / AJAX / REST)

I'attatched a few examples. Yellow = data given by API, Orange, external APIs from Streamlabs etc...

You're great! 
BreakScene
![breakscene_example](https://user-images.githubusercontent.com/8909854/28164476-d44b3af8-67cf-11e7-80e2-6437942a266a.png)
DraftScene
![draftscene_example](https://user-images.githubusercontent.com/8909854/28164474-d44a094e-67cf-11e7-8f51-372a794e6ca3.png)
IngameScene
![ingamescene_example](https://user-images.githubusercontent.com/8909854/28164475-d44b129e-67cf-11e7-8388-88053443903b.png)
MainScene
![mainscene_example](https://user-images.githubusercontent.com/8909854/28164477-d44ff9e4-67cf-11e7-9735-eb83fc634a87.png)

**Comment by kealsera** [comment]
Can't you just use an HTML which will inject all those informations to your standard OBS collection just like twitter does?

IMHO you want to achieve something via a way which is bloated with work when you can have it much easier.

**Comment by shooter92** [comment]
Yeah I can, but with if the site is stored in the web the casters don't need any files on the local computer.
They only can put in the browsersource in OBS and it's done.
But I can build a HTMLFile which does this of course. I just need to know how to get the API / Metainformations about a match by a given caster.

**Comment by kealsera** [comment]
Clarified via whispers:

API shall enable to query matches based on ID and give both teams for a given match

**Comment by kealsera** [comment]
seems to be sufficient for now, will be working throughout whenever
