### ISSUE TITLE
new roles and icons request

### ISSUE THREAD

**Issue by Takaloy** [kealsera/rikki#27]
low priority request.

1. change flex logo to something more appealing
2. as with bruiser, introduce a ranged flex role.
3. introduce icon for "no roles defined".

**Comment by kealsera** [comment]
@Takaloy Please provide those Icons :)

**Comment by Takaloy** [comment]
where are the existing roles icons stored? I can see it referencing 'assets/img/roles/' but there doesn't seem to be any roles folder in the repo.

**Comment by kealsera** [comment]
Because that's the theme repo and not this one - and there are only the roles stored which we are using OsSloth
@Takaloy 
We are using Icons from here:
http://game-icons.net/

You are free to use any other source tho - as long as it doesn't cost us anything and are SVG images.

**Comment by Takaloy** [comment]
there's a few good candidates in that library I think for flex.

http://game-icons.net/delapouite/originals/swiss-army-knife.html <- swiss army knife and all that
http://game-icons.net/sbed/originals/expander.html <-- similar to HGC's representation of Flex (they use two different colours)

---

for undefined roles this one I think is perfect: http://game-icons.net/lorc/originals/uncertainty.html

---

ranged flex could be this one: http://game-icons.net/lorc/originals/bowman.html

**Comment by kealsera** [comment]
Don't give me options, just say directly what and how and which colors if you want to change anything.

**Comment by Takaloy** [comment]
The first one then
