### ISSUE TITLE
Ruleset Change Notification

### ISSUE THREAD

**Issue by MBabiker** [kealsera/rikki#44]
Every player should be notified whenever there's a change to the ruleset. This includes heroes banned/unbanned, maps being added/removed from rotation, bugs/talents etc. This could also be done on discord (since people check that more often). Something like a "Rule Updates" channel or something could do the trick, or it could just be done in announcements

**Comment by kealsera** [comment]
We will make Bans being stored in the database by backend functionalities.

- Automated notifications for Captains on login
- Automated remove of bans when due time reached (Round bans)
- Can we have automated discord announcements with an API exposing banned heroes/talents @Astraeus- ?

**Comment by kealsera** [comment]
#45 needed

**Comment by Astraeus-** [comment]
Should be relatively simple to add if there are API endpoints.

**Comment by kealsera** [comment]
@Astraeus- /api/v1/bans

**Comment by kealsera** [comment]
@MBabiker 
![image](https://user-images.githubusercontent.com/10854875/30445796-7c7adb8c-9987-11e7-9afb-a206dabeaeb0.png)
