### ISSUE TITLE
Monitor Masterleague API

### ISSUE THREAD

**Issue by Fabian-Sommer** [kealsera/rikki#55]
Right now, they dont have the newest patch (which is 9 days old).

- [ ] remove hotfix for new talents not being present
- [ ] think about alternatives

**Comment by kealsera** [comment]
decision until season start please

**Comment by Fabian-Sommer** [comment]
As of today, they have the KTZ patch, but not the Cassia changes from 2 days ago. Continues to be unreliable

**Comment by Fabian-Sommer** [comment]
Decision: No longer use Masterleague.
