### ISSUE TITLE
Send reminder emails before season start

### ISSUE THREAD

**Issue by Fabian-Sommer** [kealsera/rikki#57]
Free Agents shall receive Emails to remind them that they signed up shortly before FAT assignment happens.

- [ ] Write a text (or delegate that to editors)
- [ ] Create email component that sends these mails
- [ ] Figure out a date
- [ ] Add email sending to schedule (or do manually)
- [ ] also think about reminders for captains

**Comment by kealsera** [comment]
@Fabian-Sommer I guess  you can set that to Season 6 as you've done that manually now

**Comment by Fabian-Sommer** [comment]
We can continue doing this manually
