### ISSUE TITLE
Deploy FAQ onto site

### ISSUE THREAD

**Issue by Fabian-Sommer** [kealsera/rikki#58]
Once it is finished

**Comment by kealsera** [comment]
Is due alongside https://github.com/kealsera/rikki/issues/52

**Comment by Fabian-Sommer** [comment]
Done in https://github.com/kealsera/rikki/commit/3856e1baa8bdfe6b81f6cd40cd0eaeb54dcae92f

**Comment by Fabian-Sommer** [comment]
Source: https://docs.google.com/document/d/1nc_HgefEgEkK18IfZSpJ_vaCECqPVeanbLHXUvkoyds/edit

**Comment by kealsera** [comment]
educational subnavigation missing.

All Blogposts being guides want to be in there as non blogposts.

**Comment by kealsera** [comment]
The FAQ being top Navigation entry commit is missing @Fabian-Sommer 
And please make sure, that it's no longer in general in our CMS as it should reflect our navigation.
