### ISSUE TITLE
Homepage for logged in members

### ISSUE THREAD

**Issue by kealsera** [kealsera/rikki#73]
Break down to important stuff for logged in people. They don't have to read up about what heroeslounge is

**Comment by phScholz** [comment]
1)Notifications/Applications
2) Current Hero Bans
3) Dates like match scheduled until/played until... Next match is on date against team
4) Important links. Differently for Captains and Players. User Profile/Team Profile/Manage Profile/etc... 
5) recent blog posts
6) recent results in the division they play in
7) standings of the division they play in
8) timeline

**Comment by kealsera** [comment]
- [ ] 1)Notifications/Applications
- [ ] 2) Current Hero Bans
- [ ] 3) Dates like match scheduled until/played until... Next match is on date against team

- [ ] 5) recent blog posts
- [ ] 6) recent results in the division they play in
- [ ] 7) standings of the division they play in
- [ ] 8) timeline

**Comment by kealsera** [comment]
Application is still open..will do maybe 😴
