### ISSUE TITLE
Perf Test DivOverview - Fixes

### ISSUE THREAD

**Issue by kealsera** [kealsera/rikki#95]
https://www.dareboost.com/en/report/59d2269e0cf235afa297b04b
https://gtmetrix.com/reports/heroeslounge.gg/BucFHlMp

Add fixes you do as comment in issue

**Comment by Fabian-Sommer** [comment]
enabled gzip compression

**Comment by kealsera** [comment]
https://gtmetrix.com/reports/heroeslounge.gg/Hes2gHXe

Test includes js .depo to async
